import{a as w,S as B,i as p}from"./assets/vendor-BSTwZ_tR.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const v=15,E="42030436-f44bf17f2fc4b636ae2b8b7a9",M="https://pixabay.com/api/";async function P(r,e=1){const{data:s}=await w.get(M,{params:{key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:v,page:e}});return s}const m=document.querySelector(".gallery"),y=document.querySelector(".loader-container"),g=document.querySelector(".load-btn"),x=new B(".gallery-item a",{captionsData:"alt",captionDelay:250});function C(r){const e=r.map(({webformatURL:s,largeImageURL:c,tags:t,likes:o,views:i,comments:S,downloads:q})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${c}">
        <img class="gallery-image" src="${s}" alt="${R(t||"")}" loading="lazy" />
        <p class="gallery-descr">
          Likes: <span class="descr-span">${o}</span>
          &nbsp; Views: <span class="descr-span">${i}</span>
          &nbsp; Comments: <span class="descr-span">${S}</span>
          &nbsp; Downloads: <span class="descr-span">${q}</span>
        </p>
      </a>
    </li>`).join("");m.insertAdjacentHTML("beforeend",e),x.refresh()}function O(){m.innerHTML=""}function $(){y.style.display="flex"}function A(){y.style.display="none"}function H(){g.classList.remove("is-hidden")}function h(){g.classList.add("is-hidden")}function R(r){return String(r).replace(/[&<>"']/g,e=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[e])}const a={form:document.querySelector(".form"),input:document.querySelector('.form input[name="search-text"]'),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-btn"),searchBtn:document.querySelector(".search-btn")};let b="",n=1,u=0,l=0,f=!1;a.form.addEventListener("submit",_);a.loadMoreBtn.addEventListener("click",z);async function _(r){r.preventDefault();const e=a.input.value.trim();if(!e)return d("The search field can't be empty! Please, enter your request!");if(e.length>100)return d("Search query must be 100 characters or less.");b=e,n=1,u=0,l=0,O(),h(),await L(),l>0&&l<u&&H()}async function z(){await L({smooth:!0}),l>=u&&(h(),p.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}async function L({smooth:r=!1}={}){if(!f){f=!0,$(),a.searchBtn.disabled=!0,a.loadMoreBtn.disabled=!0;try{const{hits:e,totalHits:s}=await P(b,n);if(n===1&&(u=s||0),!(e!=null&&e.length)){n===1&&d("Sorry, there are no images matching your search query. Please, try again!");return}C(e),l+=e.length,r&&D(),n+=1,n===2&&a.form.reset()}catch(e){console.error(e),d("Something went wrong. Please, try again later.")}finally{A(),a.searchBtn.disabled=!1,a.loadMoreBtn.disabled=!1,f=!1}}}function D(){const r=a.gallery.firstElementChild;if(!r)return;const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function d(r){p.show({class:"error-svg",position:"topRight",icon:"error-svg",message:r,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}
//# sourceMappingURL=index.js.map
